### PR TITLE
Milestone 2 sketches

### PR DESCRIPTION
**Pull request by jonaskon**

### CODE REVIEW

**Comment by nana0211** [comment]
I merged the file so as to create the milestone report.

**Comment by nana0211** [comment]
1. What is the tab GC stand for?

**Comment by nana0211** [comment]
There is no slider on the map?

**Comment by jonaskon** [comment]
> There is no slider on the map?

I forgot about that tbh, I can add it if you want

**Comment by jonaskon** [comment]
> 1. What is the tab GC stand for?

It stands for "General Classification", which is the term used in cycling for the overal standings in stage races (i.e. the added time of all the riders over all stages that were completed). It's a commonly used abbreviation, which is why I decided to use it here.

**Pull request merged**
